# Generated by Django 5.2.4 on 2025-07-14 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
